id: P006809
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:24:08.376743
source_metadata:
  id: bdr:W00KG02837
  title: རྒྱུད་བླ་མ
  author: ''
  volumes:
    571c6ba98a8d496fb09ed093041d64d1:
      image_group_id: I2KG211120
      title: ''
      volume_number: 1
      total_pages: 395
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
